; PlatformIO Project Configuration File
; Moon Patrol iBooster DAQ — ESP32 CAN sniffer + pressure logger

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

lib_deps =
    coryjfowler/mcp_can@^1.5.1
    adafruit/Adafruit ADS1X15@^2.5.0
